import os
import json
import re
from xml.parsers.expat import model
from dotenv import load_dotenv
from google import genai

load_dotenv()


def fallback_generic_schema(function_name: str = "generic_function"):
    return {
        "function_name": function_name,
        "success_output": "success",
        "fields": [
            {
                "name": "input",
                "type": "string",
                "required": True,
                "min_length": 1,
                "max_length": 100,
                "check_special_chars": True,
            }
        ],
        "expected_outputs": [
            "success",
            "input_empty",
            "input_too_long",
            "special_character_detected",
        ],
    }


def fallback_test_cases(schema: dict):
    fields = schema.get("fields", [])
    cases = []

    success_case = {
        "id": 1,
        "expected_output": schema.get("success_output", "success"),
        "description": "Valid data generated by fallback",
    }

    for field in fields:
        name = field["name"]
        field_type = field.get("type", "string")

        if field_type == "email":
            success_case[name] = "user@gmail.com"

        elif field_type in ["number", "integer"]:
            success_case[name] = max(field.get("min", 1), 1)

        elif field_type == "boolean":
            success_case[name] = True

        elif field_type == "enum":
            values = field.get("allowed_values", ["valid"])
            success_case[name] = values[0]

        else:
            min_length = field.get("min_length", 3)
            success_case[name] = "x" * max(min_length, 3)

    cases.append(success_case)

    case_id = 2

    for field in fields:
        name = field["name"]
        field_type = field.get("type", "string")

        if field.get("required", False):
            case = dict(success_case)
            case["id"] = case_id
            case[name] = ""
            case["expected_output"] = f"{name}_empty"
            case["description"] = f"Empty value for {name}"
            cases.append(case)
            case_id += 1

        if field_type == "email":
            case = dict(success_case)
            case["id"] = case_id
            case[name] = "invalid_email"
            case["expected_output"] = "invalid_email"
            case["description"] = f"Invalid email format for {name}"
            cases.append(case)
            case_id += 1

        if field_type in ["number", "integer"]:
            if "min" in field:
                case = dict(success_case)
                case["id"] = case_id
                case[name] = field["min"] - 1
                case["expected_output"] = f"invalid_{name}"
                case["description"] = f"Value smaller than min for {name}"
                cases.append(case)
                case_id += 1

            if "max" in field:
                case = dict(success_case)
                case["id"] = case_id
                case[name] = field["max"] + 1
                case["expected_output"] = f"invalid_{name}"
                case["description"] = f"Value greater than max for {name}"
                cases.append(case)
                case_id += 1

        if field_type == "string":
            if "min_length" in field:
                case = dict(success_case)
                case["id"] = case_id
                case[name] = "a"
                case["expected_output"] = f"{name}_too_short"
                case["description"] = f"Too short value for {name}"
                cases.append(case)
                case_id += 1

            if "max_length" in field:
                case = dict(success_case)
                case["id"] = case_id
                case[name] = "x" * (field["max_length"] + 5)
                case["expected_output"] = f"{name}_too_long"
                case["description"] = f"Too long value for {name}"
                cases.append(case)
                case_id += 1

        if field.get("check_special_chars", False):
            case = dict(success_case)
            case["id"] = case_id
            case[name] = "' OR '1'='1"
            case["expected_output"] = "special_character_detected"
            case["description"] = f"Special characters for {name}"
            cases.append(case)
            case_id += 1

        if field_type == "enum":
            case = dict(success_case)
            case["id"] = case_id
            case[name] = "invalid_enum_value"
            case["expected_output"] = f"invalid_{name}"
            case["description"] = f"Invalid enum value for {name}"
            cases.append(case)
            case_id += 1

    return cases


def build_prompt(input_type: str, content: str, project_name: str, function_name: str, input_schema):
    return f"""
You are a software testing expert.

The user will provide only a natural language requirement, source code, or API description.
Your task is to automatically infer the test schema and generate initial test cases.

You must return ONLY valid JSON.
Do not write markdown.
Do not write explanation.

Return exactly this JSON structure:

{{
  "schema": {{
    "function_name": "auto_detected_function_name",
    "success_output": "success_output_name",
    "fields": [
      {{
        "name": "field_name",
        "type": "string",
        "required": true,
        "min_length": 3,
        "max_length": 20,
        "min": 0,
        "max": 100,
        "allowed_values": ["value1", "value2"],
        "check_special_chars": true
      }}
    ],
    "expected_outputs": [
      "success_output",
      "field_empty",
      "field_too_short",
      "invalid_field"
    ]
  }},
  "test_cases": [
    {{
      "id": 1,
      "field_name": "value",
      "expected_output": "success_output",
      "description": "Valid test case"
    }}
  ]
}}

Important rules:

1. Infer function_name from the user's requirement.
   Example:
   - login requirement -> login
   - register requirement -> register
   - search requirement -> search
   - create product requirement -> create_product

2. Infer all input fields from the requirement.
   Example:
   - login -> username, password
   - register -> username, email, password, confirm_password
   - search -> keyword, role, status
   - product -> name, price, quantity, category

3. Infer field type:
   - text/name/username/password/keyword -> string
   - email -> email
   - age/price/amount/quantity/id -> number or integer
   - active/checked/remember_me/is_logged_in -> boolean
   - role/status/type/category with fixed options -> enum

4. Infer validation rules:
   - empty input -> field_empty
   - string too short -> field_too_short
   - string too long -> field_too_long
   - invalid email -> invalid_email
   - invalid enum -> invalid_field
   - numeric value outside min/max -> invalid_field
   - special dangerous characters -> special_character_detected

5. Infer expected_outputs from the requirement.
   All test_cases.expected_output must be inside schema.expected_outputs.

6. Generate diverse test cases:
   - valid case
   - empty required fields
   - too short strings
   - too long strings
   - invalid email
   - invalid enum
   - invalid number
   - boundary values
   - special characters
   - business cases like not_found, duplicate_data, unauthorized if mentioned

7. If the requirement mentions search and not found behavior, include not_found.

8. If the requirement mentions duplicate data, include duplicate_data or field_exists.

9. If the requirement mentions authentication/permission, include unauthorized or forbidden.

Project name: {project_name}
Suggested function name: {function_name}
Input type: {input_type}

User provided schema, if any:
{input_schema}

User requirement/code/API:
{content}
"""


def parse_test_plan(raw_text: str):
    if not raw_text:
        return None

    cleaned = raw_text.strip()
    cleaned = cleaned.replace("```json", "")
    cleaned = cleaned.replace("```", "")
    cleaned = cleaned.strip()

    try:
        data = json.loads(cleaned)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    match = re.search(r"\{.*\}", cleaned, re.DOTALL)

    if not match:
        return None

    try:
        data = json.loads(match.group(0))
        if isinstance(data, dict):
            return data
    except Exception:
        return None

    return None


def normalize_schema(schema: dict, fallback_function_name: str):
    if not schema:
        return fallback_generic_schema(fallback_function_name)

    schema.setdefault("function_name", fallback_function_name or "generic_function")
    schema.setdefault("success_output", "success")
    schema.setdefault("fields", [])
    schema.setdefault("expected_outputs", [schema["success_output"]])

    normalized_fields = []

    for field in schema.get("fields", []):
        if "name" not in field:
            continue

        field.setdefault("type", "string")
        field.setdefault("required", True)

        if field["type"] == "string":
            field.setdefault("check_special_chars", True)

        normalized_fields.append(field)

    schema["fields"] = normalized_fields

    if schema["success_output"] not in schema["expected_outputs"]:
        schema["expected_outputs"].insert(0, schema["success_output"])

    return schema


def filter_test_cases_by_schema(test_cases: list, schema: dict):
    fields = schema.get("fields", [])
    field_names = [field["name"] for field in fields]
    expected_outputs = set(schema.get("expected_outputs", []))

    filtered = []

    for index, item in enumerate(test_cases):
        case = {
            "id": index + 1,
            "expected_output": item.get("expected_output", schema.get("success_output", "success")),
            "description": item.get("description", "Generated by LLM"),
        }

        if case["expected_output"] not in expected_outputs:
            case["expected_output"] = schema.get("success_output", "success")

        for field_name in field_names:
            case[field_name] = item.get(field_name, "")

        filtered.append(case)

    return filtered


def generate_test_plan(
    input_type: str,
    content: str,
    project_name: str = "Generic Project",
    function_name: str = "auto_detect",
    input_schema=None,
):
    api_key = os.getenv("GEMINI_API_KEY")
    model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    print("========== GEMINI DEBUG ==========")
    print("API KEY EXISTS:", bool(api_key))
    print("MODEL:", model)
    print("INPUT CONTENT:", content[:200])
    print("==================================")

    # Nếu người dùng có đưa schema thì dùng schema đó.
    # Nếu không đưa schema thì để Gemini tự suy luận.
    fallback_schema = input_schema or fallback_generic_schema(function_name)

    if not api_key or api_key == "PASTE_API_KEY_CUA_MAY_VAO_DAY":
        schema = normalize_schema(fallback_schema, function_name)
        return {
            "schema": schema,
            "test_cases": fallback_test_cases(schema),
        }

    try:
        client = genai.Client(api_key=api_key)

        response = client.models.generate_content(
            model=model,
            contents=build_prompt(
                input_type=input_type,
                content=content,
                project_name=project_name,
                function_name=function_name,
                input_schema=input_schema,
            ),
        )
        print("========== GEMINI RAW RESPONSE ==========")
        print(response.text)
        print("=========================================")

        parsed = parse_test_plan(response.text)

        if not parsed:
            schema = normalize_schema(fallback_schema, function_name)
            return {
                "schema": schema,
                "test_cases": fallback_test_cases(schema),
            }

        schema = normalize_schema(
            parsed.get("schema", fallback_schema),
            function_name,
        )

        test_cases = parsed.get("test_cases", [])

        test_cases = filter_test_cases_by_schema(test_cases, schema)

        if not test_cases:
            test_cases = fallback_test_cases(schema)

        return {
            "schema": schema,
            "test_cases": test_cases,
        }

    except Exception as error:
        print("Gemini error:", error)

        schema = normalize_schema(fallback_schema, function_name)

        return {
            "schema": schema,
            "test_cases": fallback_test_cases(schema),
        }