import random

from app.services.test_harness import execute_test_suite
from app.services.fitness_service import calculate_fitness


def generate_valid_value(field: dict):
    field_type = field.get("type", "string")

    if field_type == "email":
        return "user@gmail.com"

    if field_type == "number":
        return max(field.get("min", 1), 1)

    if field_type == "integer":
        return int(max(field.get("min", 1), 1))

    if field_type == "boolean":
        return True

    if field_type == "enum":
        values = field.get("allowed_values", ["valid"])
        return values[0]

    min_length = field.get("min_length", 3)
    return "x" * max(min_length, 3)


def generate_invalid_value(field: dict):
    field_type = field.get("type", "string")
    name = field.get("name", "field")

    candidates = []

    if field.get("required", False):
        candidates.append("")

    if field.get("check_special_chars", False):
        candidates.append("' OR '1'='1")

    if field_type == "email":
        candidates.extend(["abc", "abc.com", "user@"])

    elif field_type in ["number", "integer"]:
        if "min" in field:
            candidates.append(field["min"] - 1)

        if "max" in field:
            candidates.append(field["max"] + 1)

        candidates.append("not_a_number")

    elif field_type == "string":
        if "min_length" in field:
            candidates.append("a")

        if "max_length" in field:
            candidates.append("x" * (field["max_length"] + 5))

    elif field_type == "enum":
        candidates.append("invalid_enum_value")

    elif field_type == "boolean":
        candidates.extend([True, False])

    if not candidates:
        candidates.append(f"invalid_{name}")

    return random.choice(candidates)


def random_case(schema: dict):
    case = {
        "id": 0,
        "expected_output": "unknown",
        "description": "Random generated by GA",
    }

    fields = schema.get("fields", [])

    for field in fields:
        name = field["name"]

        if random.random() < 0.55:
            case[name] = generate_valid_value(field)
        else:
            case[name] = generate_invalid_value(field)

    return case


def normalize_case(schema: dict, test_case: dict):
    normalized = {
        "id": test_case.get("id", 0),
        "expected_output": test_case.get("expected_output", "unknown"),
        "description": test_case.get("description", "Generated test case"),
    }

    for field in schema.get("fields", []):
        name = field["name"]

        if name in test_case:
            normalized[name] = test_case[name]
        else:
            normalized[name] = generate_valid_value(field)

    return normalized


def mutate_case(schema: dict, test_case: dict, mutation_rate: float = 0.35):
    new_case = dict(test_case)

    for field in schema.get("fields", []):
        name = field["name"]

        if random.random() < mutation_rate:
            if random.random() < 0.5:
                new_case[name] = generate_valid_value(field)
            else:
                new_case[name] = generate_invalid_value(field)

    return new_case


def crossover(schema: dict, parent_a: dict, parent_b: dict):
    child = {
        "id": 0,
        "expected_output": "unknown",
        "description": "Created by GA crossover",
    }

    for field in schema.get("fields", []):
        name = field["name"]
        child[name] = random.choice(
            [
                parent_a.get(name, generate_valid_value(field)),
                parent_b.get(name, generate_valid_value(field)),
            ]
        )

    return child


def repair_expected_output(schema: dict, test_case: dict):
    executed = execute_test_suite(schema, [test_case])[0]

    fixed = dict(test_case)
    fixed["expected_output"] = executed["actual_output"]

    return fixed


def case_key(schema: dict, case: dict):
    key = []

    for field in schema.get("fields", []):
        name = field["name"]
        key.append((name, str(case.get(name))))

    return tuple(key)


def run_genetic_algorithm(
    schema: dict,
    initial_cases: list,
    generations: int = 20,
    population_size: int = 16,
):
    population = [normalize_case(schema, case) for case in initial_cases]

    while len(population) < population_size:
        population.append(random_case(schema))

    population = [repair_expected_output(schema, case) for case in population]

    best_population = population
    best_fitness = calculate_fitness(schema, execute_test_suite(schema, best_population))

    for _ in range(generations):
        children = []

        for _ in range(population_size):
            parent_a = random.choice(population)
            parent_b = random.choice(population)

            child = crossover(schema, parent_a, parent_b)
            child = mutate_case(schema, child)
            child = repair_expected_output(schema, child)

            children.append(child)

        combined = population + children
        scored = []

        for item in combined:
            temp_suite = execute_test_suite(schema, [item])
            score = calculate_fitness(schema, temp_suite)
            scored.append((score, item))

        scored.sort(key=lambda x: x[0], reverse=True)

        population = [item for _, item in scored[:population_size]]

        current_fitness = calculate_fitness(schema, execute_test_suite(schema, population))

        if current_fitness > best_fitness:
            best_fitness = current_fitness
            best_population = population

        if best_fitness >= 100:
            break

    final_population = []
    seen = set()

    for case in best_population:
        key = case_key(schema, case)

        if key not in seen:
            seen.add(key)
            final_population.append(repair_expected_output(schema, case))

    return final_population